Console.log("=== Vec2 二维向量 ===");
let vec2A = new Vec2(1, 2);
let vec2B = new Vec2(3, 4);
Console.log("v2a:", vec2A.toString());
Console.log("v2a.x:", vec2A.x, "v2a.y:", vec2A.y);
let vec2Sum = vec2A.add(vec2B);
Console.log("v2a + v2b:", vec2Sum.toString());
let vec2Diff = vec2A.sub(vec2B);
Console.log("v2a - v2b:", vec2Diff.toString());
let vec2Mul2 = vec2A.multiply(2);
Console.log("v2a * 2:", vec2Mul2.toString());
let vec2Scaled3 = vec2A.scale(3);
Console.log("v2a.scale(3):", vec2Scaled3.toString());
let dot2Val = vec2A.dot(vec2B);
Console.log("v2a.dot(v2b):", dot2Val);
let len2Val = vec2A.len();
Console.log("v2a.len():", len2Val);
let dist2Val = vec2A.distance(vec2B);
Console.log("v2a.distance(v2b):", dist2Val);
let vec2Norm = vec2A.normalize();
Console.log("v2a.normalize():", vec2Norm.toString());
let vec2Neg = vec2A.negate();
Console.log("v2a.negate():", vec2Neg.toString());
let vec2Clone = vec2A.clone();
Console.log("v2a.clone():", vec2Clone.toString());
let eq2Val = vec2A.equals(vec2Clone);
Console.log("v2a.equals(v2i):", eq2Val);

Console.log("\n=== Vec3 三维向量 ===");
let vec3A = new Vec3(1, 2, 3);
let vec3B = new Vec3(4, 5, 6);
Console.log("v3a:", vec3A.toString());
Console.log("v3a.x:", vec3A.x, "v3a.y:", vec3A.y, "v3a.z:", vec3A.z);
let vec3Sum = vec3A.add(vec3B);
Console.log("v3a + v3b:", vec3Sum.toString());
let vec3Diff = vec3A.sub(vec3B);
Console.log("v3a - v3b:", vec3Diff.toString());
let vec3Mul2 = vec3A.multiply(2);
Console.log("v3a * 2:", vec3Mul2.toString());
let vec3ScaledHalf = vec3A.scale(0.5);
Console.log("v3a.scale(0.5):", vec3ScaledHalf.toString());
let dot3Val = vec3A.dot(vec3B);
Console.log("v3a.dot(v3b):", dot3Val);
let cross3Val = vec3A.cross(vec3B);
Console.log("v3a.cross(v3b):", cross3Val.toString());
let len3Val = vec3A.len();
Console.log("v3a.len():", len3Val);
let dist3Val = vec3A.distance(vec3B);
Console.log("v3a.distance(v3b):", dist3Val);
let vec3Norm = vec3A.normalize();
Console.log("v3a.normalize():", vec3Norm.toString());
let vec3Neg = vec3A.negate();
Console.log("v3a.negate():", vec3Neg.toString());
let vec3Clone = vec3A.clone();
Console.log("v3a.clone():", vec3Clone.toString());
let eq3Val = vec3A.equals(vec3Clone);
Console.log("v3a.equals(v3i):", eq3Val);
let angle3Val = vec3A.angle(vec3B);
Console.log("v3a.angle(v3b):", angle3Val);
let vec3Lerp = vec3A.lerp(vec3B, 0.5);
Console.log("v3a.lerp(v3b, 0.5):", vec3Lerp.toString());

Console.log("\n=== Vec4 四维向量 ===");
let vec4A = new Vec4(1, 2, 3, 4);
let vec4B = new Vec4(5, 6, 7, 8);
Console.log("v4a:", vec4A.toString());
Console.log("v4a.x:", vec4A.x, "v4a.y:", vec4A.y, "v4a.z:", vec4A.z, "v4a.w:", vec4A.w);
let vec4Sum = vec4A.add(vec4B);
Console.log("v4a + v4b:", vec4Sum.toString());
let vec4Diff = vec4A.sub(vec4B);
Console.log("v4a - v4b:", vec4Diff.toString());
let vec4Mul2 = vec4A.multiply(2);
Console.log("v4a * 2:", vec4Mul2.toString());
let dot4Val = vec4A.dot(vec4B);
Console.log("v4a.dot(v4b):", dot4Val);
let len4Val = vec4A.len();
Console.log("v4a.len():", len4Val);
let vec4Norm = vec4A.normalize();
Console.log("v4a.normalize():", vec4Norm.toString());
let vec4Clone = vec4A.clone();
Console.log("v4a.clone():", vec4Clone.toString());
