Console.log("=== Mat3 3x3矩阵 ===");
var m3a = new Mat3();
m3a.identity();
Console.log("m3a identity:", m3a.toString());
var m3b = new Mat3();
m3b.set(1, 0, 0, 0, 2, 0, 0, 0, 3);
Console.log("m3b:", m3b.toString());
var det3 = m3b.determinant();
Console.log("m3b.determinant():", det3);
var m3c = m3b.transpose();
Console.log("m3b.transpose():", m3c.toString());
var m3d = m3b.inverse();
Console.log("m3b.inverse():", m3d.toString());
var m3e = m3b.clone();
Console.log("m3b.clone():", m3e.toString());

Console.log("\n=== Mat3 变换 ===");
var m3trans = new Mat3();
m3trans.identity();
m3trans.translate(new Vec2(10, 20));
Console.log("m3trans.translate(Vec2(10,20)):", m3trans.toString());
var m3rot = new Mat3();
m3rot.identity();
var angle1 = Math.PI / 4;
m3rot.rotate(angle1);
Console.log("m3rot.rotate(PI/4):", m3rot.toString());
var m3scale = new Mat3();
m3scale.identity();
m3scale.scale(new Vec2(2, 3));
Console.log("m3scale.scale(Vec2(2,3)):", m3scale.toString());

Console.log("\n=== Mat4 4x4矩阵 ===");
var m4a = new Mat4();
m4a.identity();
Console.log("m4a identity:", m4a.toString());
var m4b = new Mat4();
m4b.set(1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1);
Console.log("m4b:", m4b.toString());
var det4 = m4b.determinant();
Console.log("m4b.determinant():", det4);
var m4c = m4b.transpose();
Console.log("m4b.transpose():", m4c.toString());
var m4d = m4b.inverse();
Console.log("m4b.inverse():", m4d.toString());
var m4e = m4b.clone();
Console.log("m4b.clone():", m4e.toString());

Console.log("\n=== Mat4 变换 ===");
var m4trans = new Mat4();
m4trans.identity();
m4trans.translate(new Vec3(10, 20, 30));
Console.log("m4trans.translate(Vec3(10,20,30)):", m4trans.toString());
var m4rot = new Mat4();
m4rot.identity();
var angleX = Math.PI / 4;
m4rot.rotate(angleX, new Vec3(1, 0, 0));
Console.log("m4rot.rotate(PI/4, X轴):", m4rot.toString());

Console.log("\n=== Mat4 投影矩阵 ===");
var m4persp = new Mat4();
var fov = Math.PI / 4;
var aspect = 16 / 9;
m4persp.perspective(fov, aspect, 0.1, 100);
Console.log("m4persp.perspective():", m4persp.toString());

Console.log("\n=== Mat4 视图矩阵 ===");
var m4look = new Mat4();
m4look.lookAt(new Vec3(0, 0, 5), new Vec3(0, 0, 0), new Vec3(0, 1, 0));
Console.log("m4look.lookAt():", m4look.toString());